
###
POST http://localhost:38475/odata/v4/awards-service-employee/b9q2fsan18bqxar0
Content-Type: application/json

{"D4OXYPALUYAIDNSO": "{\"AwardDetails\":{\"AWRID\":0,\"EMPID\":\"SLS1379\",\"AWARD\":10,\"ACMNT\":1,\"CATEG\":27,\"CNAME\":\"Certification Name\",\"NOTES\":\"Notes\",\"STATS\":31,\"REPBY\":\"SLS1160\",\"REPDT\":\"2026-03-06\",\"AWRDT\":\"2026-03-06\"}}"}


###
{"D4OXYPALUYAIDNSO":"{\"AwardDetails\":{\"AWRID\":0,\"EMPID\":\"SLS1379\",\"AWARD\":10,\"ACMNT\":1, \"CATEG\":27, \"NOTES\":\"Notes\", \"STATS\":31, \"REPBY\":\"SLS1160\",\"REPDT\":\"2026-03-06\",\"AWRDT\":\"2026-03-06\", \"Attachments\": [{\"ATHID\":0,\"ATTNM\":\"Attachment Name\",\"TITLE\":\"Title\",\"URLDT\":\"URL1\" }, {\"ATHID\":0,\"ATTNM\":\"Attachment Name2\",\"TITLE\":\"Title2\",\"URLDT\":\"URL2\" }]}}"}
 
###

POST http://localhost:40711/odata/v4/awards-service-employee/T5qTMWJSg36f8E6y
Content-Type: application/json

{"D4OXYPALUYAIDNSO": "U2FsdGVkX1/zSvHaoiPUVkSmbn9ICgpimJJ3khLoCgBrPDoehkoQ40L5Gg+n+PW/IisxDs5QTAVNX+mnHVCVyFdqaP20HSC0zkjpqp75UWzx2ppKHLu5Za+k9XeO5XKk8CJUuiaqZSPPeGg8N3wkypf87wNlJusmgbGXShbpUsutR3gj7+YJPPCSlny3c+nS5myC2ch7E0wds5dtTAArobDPRo9xNObVad4F1XSt8OGWVkRkKC8pgKZO1vLiafdF"}



###

{"D4OXYPALUYAIDNSO": "{\"AwardDetails_Attach\":{\"Attachments\":[{\"ATHID\":47,\"AWRID\":50,\"ATTNM\":\"Attachment Name\",\"TITLE\":\"Title\",\"URLDT\":\"URL1\"},{\"ATHID\":48,\"AWRID\":50,\"ATTNM\":\"Attachment Name2\",\"TITLE\":\"Title2\",\"URLDT\":\"URL2\"}]}}"}
